---
title: "db_build"
format: html
editor: source
---

### Load Packages

```{r}
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

librarian::shelf(DBI, RPostgres)
```

### connect to `RIBBiTR` database
```{r}

tryCatch({
    drv <- dbDriver("Postgres")
    print("Connecting to Database…")
    connection <- dbConnect(drv, 
                 dbname = Sys.getenv("aws_dbname"),
                 host = Sys.getenv("aws_host"), 
                 port = Sys.getenv("aws_port"),
                 user = Sys.getenv("aws_user"), 
                 password = Sys.getenv("aws_password"),
                 timezone=NULL)
    print("Database Connected!")
    },
    error=function(cond) {
            print("Unable to connect to Database.")
    })

# set search path
dbExecute(connection, "set search_path = 'kira_pep';")

```

### Build Relationships
```{r}

# visit table
dbExecute(connection, "alter table visit add primary key(visit_id);")


# survey table
dbExecute(connection, "alter table survey add primary key(survey_id);")

dbExecute(connection,
          "alter table survey  
           add constraint fk_survey foreign key (visit_id) 
          references visit (visit_id);")

# ves table
dbExecute(connection, "alter table ves add primary key(ves_id);")

dbExecute(connection,           
          "alter table ves  
          add constraint fk_ves foreign key (survey_id) 
          references survey (survey_id);")

# capture table
dbExecute(connection, "alter table capture add primary key(capture_id);")

dbExecute(connection,
          "alter table capture  
          add constraint fk_cap foreign key (survey_id) 
          references survey (survey_id);")
```

