---
title: "Data Wrangle"
format: html
editor: visual
---

### Load Packages
```{r}
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

librarian::shelf(tidyverse, here, janitor)
```

### Loop to Read in Data
```{r}

filenames <- gsub("\\.csv$","", list.files(here("data", "raw")))

for(i in filenames){
  assign(i, read_csv(here("data", "raw", paste(i, ".csv", sep=""))))
}


```

### Clean `pep_kira` - `visit`
```{r}

clean_visit <- pep_kira %>% 
  clean_names() %>% 
  select(!c(created_at:geometry)) %>% 
  rename(visit_id = fulcrum_id)
  
write_csv(clean_visit, here("data", "clean", "visit.csv"))

```

### Clean `pep_kira_description` - `survey`
```{r}

clean_survey <- pep_kira_description %>% 
  clean_names() %>% 
  select(!c(fulcrum_record_id:updated_by, photos_desc:photos_desc_url)) %>% 
  rename(visit_id = fulcrum_parent_id,
         survey_id = fulcrum_id)
  

write_csv(clean_survey, here("data", "clean", "survey.csv"))

```

### Clean `pep_kira_description_amphibian_capture` - `capture`
```{r}

clean_capture <- pep_kira_description_amphibian_capture %>% 
  clean_names() %>% 
  select(!c(fulcrum_record_id:updated_by)) %>% 
  rename(capture_id = fulcrum_id,
         survey_id = fulcrum_parent_id)

write_csv(clean_capture, here("data", "clean", "capture.csv"))

```

### Clean `pep_kira_description_animal_counts` - `VES`
```{r}

clean_ves <- pep_kira_description_animal_counts %>% 
  clean_names() %>% 
  select(!c(fulcrum_record_id:updated_by)) %>% 
  rename(ves_id = fulcrum_id,
         survey_id = fulcrum_parent_id)

write_csv(clean_ves, here("data", "clean", "ves.csv"))

```

### Join all tables together - `fulcrum_id` = `fulcrum_parent_id`
#### `visit` to `survey`
```{r}

clean_vis_sur <- clean_visit %>% 
  left_join(clean_survey, by = c("visit_id")) %>% 
  select(!c(visit_id))
  

```

#### `Capture` data
```{r}

capture_data <- clean_vis_sur %>% 
  left_join(clean_capture, by = c("survey_id")) %>% 
  select(!c(survey_id, capture_id)) %>% 
  filter(!visit_date <= "2023-07-01") #remove all data before July


```

#### `VES` data
```{r}

ves_data <- clean_vis_sur %>% 
  left_join(clean_ves, by = c("survey_id")) %>% 
  select(!c(survey_id, ves_id)) %>% 
  filter(!visit_date <= "2023-07-01") #remove all data before July

```